apiVersion: v1
kind: Pod
metadata:
  name: oom-tracker
spec:
  shareProcessNamespace: true
  containers:
    - name: leaker
      image: gigiozzz/leaker:latest
      imagePullPolicy: Always
      livenessProbe:
        periodSeconds: 3
        failureThreshold: 1
        httpGet:
          path: /healthz
          port: 8080
      resources:
        requests:
          memory: "25Mi"
          cpu: "250m"
        limits:
          memory: "50Mi"
          cpu: "250m"
    - name: oom-tracker
      image: gigiozzz/oom-tracker:latest
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
      - name: WARNING
        value: "65"
      - name: CRITICAL
        value: "90" 
      resources: {}